version: '3.8'

services:
  db_layoffs:
    image: postgres:15-alpine
    container_name: postgres_layoffs
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: tech_layoffs_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: